### ISSUE TITLE
npm run start fails

### ISSUE THREAD

**Issue by fredski02** [express-vue/express-vue-mvc-starter#18]
Windows : 10
npm : 5.5.1
node : 8.9.1

Here is the error code 

`C:\Users\fredski\Desktop\vue-projects\express-vue (master)
λ npm run start

> express-vue@1.0.0 start C:\Users\fredski\Desktop\vue-projects\express-vue
> gulp

[16:41:04] Requiring external module babel-register
fs.js:904
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\fredski\Desktop\vue-projects\express-vue\node_modules\node-sass\vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (C:\Users\fredski\Desktop\vue-projects\express-vue\node_modules\node-sass\lib\extensions.js:124:13)
    at foundBinariesList (C:\Users\fredski\Desktop\vue-projects\express-vue\node_modules\node-sass\lib\errors.js:20:15)
    at foundBinaries (C:\Users\fredski\Desktop\vue-projects\express-vue\node_modules\node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (C:\Users\fredski\Desktop\vue-projects\express-vue\node_modules\node-sass\lib\errors.js:45:5)
    at module.exports (C:\Users\fredski\Desktop\vue-projects\express-vue\node_modules\node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (C:\Users\fredski\Desktop\vue-projects\express-vue\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:635:30)
    at Module._extensions..js (module.js:646:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\fredski\Desktop\vue-projects\express-vue\node_modules\babel-register\lib\node.js:152:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! express-vue@1.0.0 start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the express-vue@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\fredski\AppData\Roaming\npm-cache\_logs\2017-11-18T16_41_04_700Z-debug.log`

**Comment by arxpw** [comment]
Installing node-sass individually:
`npm install node-sass`

Resolved this issue for me, give it a go?

**Comment by danmademe** [comment]
yes if you're using anything other than vanilla ... you will need to install those tools..

similar to babel... so yes you need node sass if you are using sass/scss in your templates
