### ISSUE TITLE
error in index.js

### ISSUE THREAD

**Issue by xtrimf** [express-vue/express-vue-mvc-starter#8]
express-vue-mvc-starter/app/index.js:13
    let workers: Object[] = [];
               ^

SyntaxError: Unexpected token :
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

**Comment by danmademe** [comment]
Did you npm install before npm run?

The invalid token is flow typing. It means you don’t have flow installed. It’s installed when you install the package. I’ll double check that Monday.

**Comment by danmademe** [comment]
Yes it’s there. Npm runs gulp which runs babel which runs flow.

**Comment by xtrimf** [comment]
> Did you npm install before npm run?

yeap

**Comment by danmademe** [comment]
Ok I’ll take a look Monday. I’ll probably just strip out the flow typing.

**Comment by danmademe** [comment]
updated now.. pull and run npm install
